version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=PLouto -Dsonar.organization=Plouto -Dsonar.host.url=https://sonarcould.io -Dsonar.login=6430ce93cfa278238981bd58e6e83e17e47e9ba2
